name: OCR Dolar

on:
  workflow_dispatch:

jobs:
  run:
    runs-on: ubuntu-latest

    steps:

      - uses: actions/checkout@v4

      - uses: actions/setup-python@v5
        with:
          python-version: "3.12"

      - run: pip install -r requirements.txt

      - run: playwright install chromium

      - run: python scraper.py

      - uses: actions/upload-artifact@v4
        with:
          name: captura
          path: captura.png

          
      - run: python scraper.py
        env:
          OCR_API_KEY: ${{ secrets.OCR_API_KEY }}

